### ISSUE TITLE
Printed PDF in Safari is scaled

### ISSUE THREAD

**Issue by rsayfutdinov** [hrynko/vue-pdf-embed#115]
Hello,

Pdfs are zoomed in while printing from Safari (Version 16.2 (18614.3.7.1.5))
See attached screenshots Safari vs. Firefox

<img width="858" alt="Screenshot 2023-02-02 at 14 03 04" src="https://user-images.githubusercontent.com/12187524/216332579-331a8634-a5f8-40f9-8cfc-71f6459d4083.png">

<img width="1105" alt="Screenshot 2023-02-02 at 14 04 05" src="https://user-images.githubusercontent.com/12187524/216332570-4cb3bc6d-a792-4e03-8142-3176e809a008.png">

**Comment by hrynko** [comment]
Hi @rsayfutdinov,

Looks like a limited support of [@page](https://developer.mozilla.org/en-US/docs/Web/CSS/@page) in Safari. I'll try to revisit this later.

**Comment by hrynko** [comment]
It was fixed and published in `1.1.6`

Thanks for discovering this issue

**Comment by Ceda** [comment]
The problem persists even after updating to v 1.1.6, in Safari, the PDF preview is generated on two pages. After reducing to 93%, the display is correct.
<img width="832" alt="image" src="https://github.com/hrynko/vue-pdf-embed/assets/1154301/48e87412-c731-4552-894e-3c640e6ff8d0">
